% Script to crop white-space from Figures generated by MRIcroGL
basepath='/Users/matthiaszunhammer/Dropbox/Boulder_Essen/Protocol_and_Manuscript/whole_brain/figures/'
picpaths=dir([basepath,'*.png']);
picpaths=strcat(basepath,{picpaths.name});
for i=1:length(picpaths)
    crop(picpaths{i});
end

fig2_paths={
        'Figure_2_Render_ant.png'
        'Figure_2_Render_left.png'
        'Figure_2_Render_right.png'
        'Figure_2_Render_post.png'
        'Figure_2_Render_cut_insula.png'
        'Figure_2_Render_cut_medial_left.png'
        'Figure_2_Render_cut_medial_right.png'
        'Figure_2_Render_post_cerebellum.png'
    };