function D_WB_meta_analysis_p_values(datapath)
%% Create thresholds:

% Add permutation summary to statistical summary struct
p = mfilename('fullpath'); %CANlab's apply mask do not like relative paths so this cludge is needed
[p,~,~]=fileparts(p);
splitp=strsplit(p,'/');
whole_brain_path=fullfile(filesep,splitp{1:end-1});
results_path=fullfile(whole_brain_path,'vectorized_results');

load(fullfile(results_path,'WB_summary_pain_full.mat'),...
    'summary_pain');
load(fullfile(results_path,'WB_summary_placebo_full.mat'),...
    'summary_placebo');

%% Pain
[summary_pain.g.fixed.perm.p_uncorr,...
 summary_pain.g.fixed.perm.p_FWE]=p_perm(summary_pain.g.fixed.z_smooth,... %original stat
                                 summary_pain.g.fixed.perm.z_dist,...    %permutation object
                                 'two-tailed');                               %tails object

[summary_pain.g.random.perm.p_uncorr,...
 summary_pain.g.random.perm.p_FWE]=p_perm(summary_pain.g.random.z_smooth,...
                                  summary_pain.g.random.perm.z_dist,...
                                  'two-tailed');
% [summary_pain.g.heterogeneity.perm.p_uncorr,...
%  summary_pain.g.heterogeneity.perm.p_FWE]=p_perm(summary_pain.g.heterogeneity.chisq,...
%                                          summary_pain.g.heterogeneity.perm.chi_dist,...
%                                          'one-tailed-larger');
%% Placebo

% g
[summary_placebo.g.fixed.perm.p_uncorr,...
 summary_placebo.g.fixed.perm.p_FWE]=p_perm(summary_placebo.g.fixed.z_smooth,... %original stat
                                 summary_placebo.g.fixed.perm.z_dist,...    %permutation object
                                 'two-tailed');                               %tails object
[summary_placebo.g.random.perm.p_uncorr,...
 summary_placebo.g.random.perm.p_FWE]=p_perm(summary_placebo.g.random.z_smooth,...
                                  summary_placebo.g.random.perm.z_dist,...
                                  'two-tailed');

% [summary_placebo.g.heterogeneity.perm.p_uncorr,...
%  summary_placebo.g.heterogeneity.perm.p_FWE]=p_perm(summary_placebo.g.heterogeneity.chisq,...
%                                         summary_placebo.g.heterogeneity.perm.chi_dist,...
%                                         'one-tailed-larger');
% correlation with behavior
[summary_placebo.r_external.fixed.perm.p_uncorr,...
 summary_placebo.r_external.fixed.perm.p_FWE]=p_perm(summary_placebo.r_external.fixed.z_smooth,... %original stat
                                 summary_placebo.r_external.fixed.perm.z_dist,...    %permutation object
                                 'two-tailed');                               %tails object
[summary_placebo.r_external.random.perm.p_uncorr,...
 summary_placebo.r_external.random.perm.p_FWE]=p_perm(summary_placebo.r_external.random.z_smooth,...
                                  summary_placebo.r_external.random.perm.z_dist,...
                                  'two-tailed');
% [summary_placebo.r_external.heterogeneity.perm.p_uncorr,...
% summary_placebo.r_external.heterogeneity.perm.p_FWE]=p_perm(summary_placebo.r_external.heterogeneity.chisq,...
%                                         summary_placebo.r_external.heterogeneity.perm.chi_dist,...
%                                         'one-tailed-larger');

save(fullfile(results_path,'WB_summary_pain_full.mat'),...
    'summary_pain','-append');

save(fullfile(results_path,'WB_summary_placebo_full.mat'),...
    'summary_placebo','-append');