function K_sub_group_analysis_left_heat(datapath,pubpath)
% Analysis in response to letter by
% Clas Linnman & Leon Morales-Quezada
addpath(genpath(analysispath));
df_name='data_frame.mat';
load(fullfile(datapath,df_name),'df');
heat_studies=ismember(df.stim_type,{'contact heat'});
left_body_side_studies=logical([1,0,0,1,1,1,0,0,1,1,0,0,0,1,0,0,0,1,1,0]');
condi_studies=ismember(df.placebo_induction,{'suggestions & conditioning','conditioning'});

X=[heat_studies,left_body_side_studies];
% with interaction: X=[heat_studies,left_body_side_studies,heat_studies.*left_body_side_studies];

y_pain=[df.GIV_stats_pain_NPS.g];
se_y_pain=[df.GIV_stats_pain_NPS.se_g];
summary_stat_pain=GIV_weight(y_pain',se_y_pain');
w1=summary_stat_pain.weight;
w2=summary_stat_pain.rel_weight;
lm_pain=fitlm(X,y_pain,'Weights',w1)

y_out_pain=...
[lm_pain.Coefficients.Estimate(1),... %not left, not heat
 lm_pain.Coefficients.Estimate(1)+lm_pain.Coefficients.Estimate(2),... %not left, heat
 lm_pain.Coefficients.Estimate(1)+lm_pain.Coefficients.Estimate(3),... %left, not heat
 lm_pain.Coefficients.Estimate(1)+lm_pain.Coefficients.Estimate(2)+lm_pain.Coefficients.Estimate(3)+lm_pain.Coefficients.Estimate(4),... %heat and left
  ]
bar(y_out_pain);
%errorbar(x,y,err)


y_pla=[df.GIV_stats_NPS.g];
se_y_pla=[df.GIV_stats_NPS.se_g];
summary_stat_pla=GIV_weight(y_pla',se_y_pla');
w1=summary_stat_pla.weight;
w2=summary_stat_pla.rel_weight;
lm_pla=fitlm(X,y_pla,'Weights',w1)

y_out_pla=...
[lm_pla.Coefficients.Estimate(1),... %not left, not heat
 lm_pla.Coefficients.Estimate(1)+lm_pla.Coefficients.Estimate(2),... %not left, heat
 lm_pla.Coefficients.Estimate(1)+lm_pla.Coefficients.Estimate(3),... %left, not heat
 lm_pla.Coefficients.Estimate(1)+lm_pla.Coefficients.Estimate(2)+lm_pla.Coefficients.Estimate(3)+lm_pla.Coefficients.Estimate(4),... %heat and left
  ];
bar(y_out_pla);
%% Analysis NPS PAIN heat_studies 
summary_NPS_pla_heat=forest_plotter(df.GIV_stats_pain_NPS(heat_studies),...
              'study_ID_texts',df.study_citations(heat_studies),...
              'outcome_label','NPS response (Hedges''g)',...
              'type','random',...
              'summary_stat','g',...
              'with_outlier',0,...
              'WI_subdata',{},...
              'box_scaling',1,...
              'X_scale',6);

hgexport(gcf, fullfile(pubpath,'NPS_pain_heat_studies'), hgexport('factorystyle'), 'Format', 'svg');
hgexport(gcf, fullfile(pubpath,'NPS_pain_heat_studies'), hgexport('factorystyle'), 'Format', 'png');
crop(fullfile(pubpath,'NPS_pain_heat_studies.png'));

%% Analysis NPS PAIN non_heat_studies 
summary_NPS_pla_nonheat=forest_plotter(df.GIV_stats_pain_NPS(~heat_studies),...
              'study_ID_texts',df.study_citations(~heat_studies),...
              'outcome_label','NPS response (Hedges''g)',...
              'type','random',...
              'summary_stat','g',...
              'with_outlier',0,...
              'WI_subdata',{},...
              'box_scaling',1,...
              'X_scale',6);

hgexport(gcf, fullfile(pubpath,'NPS_pain_non_heat_studies'), hgexport('factorystyle'), 'Format', 'svg');
hgexport(gcf, fullfile(pubpath,'NPS_pain_non_heat_studies'), hgexport('factorystyle'), 'Format', 'png');
crop(fullfile(pubpath,'NPS_pain_non_heat_studies.png'));


%% Analysis NPS placebo  heat_studies
summary_NPS_pla_heat=forest_plotter(df.GIV_stats_NPS(heat_studies),...
              'study_ID_texts',df.study_citations(heat_studies),...
              'outcome_label','NPS response (Hedges''g)',...
              'type','random',...
              'summary_stat','g',...
              'with_outlier',0,...
              'WI_subdata',{},...
              'box_scaling',1,...
              'X_scale',2);

hgexport(gcf, fullfile(pubpath,'NPS_placebo_heat_studies'), hgexport('factorystyle'), 'Format', 'svg');
hgexport(gcf, fullfile(pubpath,'NPS_placebo_heat_studies'), hgexport('factorystyle'), 'Format', 'png');
crop(fullfile(pubpath,'NPS_placebo_heat_studies.png'));

%% Analysis NPS placebo non_heat_studies 
summary_NPS_pla_nonheat=forest_plotter(df.GIV_stats_NPS(~heat_studies),...
              'study_ID_texts',df.study_citations(~heat_studies),...
              'outcome_label','NPS response (Hedges''g)',...
              'type','random',...
              'summary_stat','g',...
              'with_outlier',0,...
              'WI_subdata',{},...
              'box_scaling',1,...
              'X_scale',2);

hgexport(gcf, fullfile(pubpath,'NPS_placebo_non_heat_studies'), hgexport('factorystyle'), 'Format', 'svg');
hgexport(gcf, fullfile(pubpath,'NPS_placebo_non_heat_studies'), hgexport('factorystyle'), 'Format', 'png');
crop(fullfile(pubpath,'NPS_placebo_non_heat_studies.png'));






%% Analysis NPS PAIN left_body_side_studies 
summary_NPS_pla_heat=forest_plotter(df.GIV_stats_pain_NPS(left_body_side_studies),...
              'study_ID_texts',df.study_citations(left_body_side_studies),...
              'outcome_label','NPS response (Hedges''g)',...
              'type','random',...
              'summary_stat','g',...
              'with_outlier',0,...
              'WI_subdata',{},...
              'box_scaling',1,...
              'X_scale',6);

hgexport(gcf, fullfile(pubpath,'NPS_pain_left_body_side_studies'), hgexport('factorystyle'), 'Format', 'svg');
hgexport(gcf, fullfile(pubpath,'NPS_pain_left_body_side_studies'), hgexport('factorystyle'), 'Format', 'png');
crop(fullfile(pubpath,'NPS_pain_left_body_side_studies.png'));

%% Analysis NPS PAIN left_body_side_studies 
summary_NPS_pla_nonheat=forest_plotter(df.GIV_stats_pain_NPS(~left_body_side_studies),...
              'study_ID_texts',df.study_citations(~left_body_side_studies),...
              'outcome_label','NPS response (Hedges''g)',...
              'type','random',...
              'summary_stat','g',...
              'with_outlier',0,...
              'WI_subdata',{},...
              'box_scaling',1,...
              'X_scale',6);

hgexport(gcf, fullfile(pubpath,'NPS_pain_non_left_body_side_studies'), hgexport('factorystyle'), 'Format', 'svg');
hgexport(gcf, fullfile(pubpath,'NPS_pain_non_left_body_side_studies'), hgexport('factorystyle'), 'Format', 'png');
crop(fullfile(pubpath,'NPS_pain_non_left_body_side_studies.png'));


%% Analysis NPS placebo  left_body_side_studies
summary_NPS_pla_heat=forest_plotter(df.GIV_stats_NPS(left_body_side_studies),...
              'study_ID_texts',df.study_citations(left_body_side_studies),...
              'outcome_label','NPS response (Hedges''g)',...
              'type','random',...
              'summary_stat','g',...
              'with_outlier',0,...
              'WI_subdata',{},...
              'box_scaling',1,...
              'X_scale',2);

hgexport(gcf, fullfile(pubpath,'NPS_placebo_left_body_side_studies'), hgexport('factorystyle'), 'Format', 'svg');
hgexport(gcf, fullfile(pubpath,'NPS_placebo_left_body_side_studies'), hgexport('factorystyle'), 'Format', 'png');
crop(fullfile(pubpath,'NPS_placebo_left_body_side_studies.png'));

%% Analysis NPS placebo left_body_side_studies 
summary_NPS_pla_nonheat=forest_plotter(df.GIV_stats_NPS(~left_body_side_studies),...
              'study_ID_texts',df.study_citations(~left_body_side_studies),...
              'outcome_label','NPS response (Hedges''g)',...
              'type','random',...
              'summary_stat','g',...
              'with_outlier',0,...
              'WI_subdata',{},...
              'box_scaling',1,...
              'X_scale',2);

hgexport(gcf, fullfile(pubpath,'NPS_placebo_non_left_body_side_studies'), hgexport('factorystyle'), 'Format', 'svg');
hgexport(gcf, fullfile(pubpath,'NPS_placebo_non_left_body_side_studies'), hgexport('factorystyle'), 'Format', 'png');
crop(fullfile(pubpath,'NPS_placebo_non_left_body_side_studies.png'));