function K_sub_group_open_hidden_vs_rest(datapath,pubpath)
%% Comparison of open/hidden vs other placebo studies
df_name='data_frame.mat';
load(fullfile(datapath,df_name),'df');

stats.condi=...
   {'Open vs hidden'               %	'atlas'
    'Placebo vs no placebo'%   'bingel'
    'Open vs hidden'%   'bingel11'
    'Placebo vs no placebo'%   'choi'
    'Placebo vs no placebo'%   'eippert'
    'Placebo vs no treatment'      %   'ellingsen'
    'Placebo vs no placebo'      %   'elsenbruch'
    'Placebo vs no placebo'    %   'freeman'
    'Placebo vs no placebo'   %   'geuter'
    'Placebo vs no placebo'     %   'kessner'
    'Placebo vs no placebo'    %   'kong06'
    'Placebo vs no placebo'    %   'kong09'
    'Placebo vs no placebo'    %   'lui'
    'Placebo vs no treatment'    %   'ruetgen'
    'Open vs hidden'      %   'schenk'
    'Placebo vs no placebo'     %   'theysohn'
    'Placebo vs no placebo'     %   'wager04a_princeton'
    'Placebo vs no placebo'    %   'wager04b_michigan'
    'Placebo vs no placebo'    %   'wrobel'
    'Placebo vs no treatment'    };%  'zeidan'

open_hidden=strcmp(stats.condi,'Open vs hidden');
placebo_control=strcmp(stats.condi,'Placebo vs no placebo');
placebo_notreatment=strcmp(stats.condi,'Placebo vs no treatment');


%% Analysis for ratings
summary_rating_open_hidden=forest_plotter(df.GIV_stats_rating(open_hidden),...
              'study_ID_texts',df.study_citations(open_hidden),...
              'outcome_label','Pain ratings (Hedges''g)',...
              'type','random',...
              'summary_stat','g',...
              'with_outlier',0,...
              'WI_subdata',{},...
              'box_scaling',1,...
              'X_scale',2);

hgexport(gcf, fullfile(pubpath,'Rating_Open_Hidden'), hgexport('factorystyle'), 'Format', 'svg');
hgexport(gcf, fullfile(pubpath,'Rating_Open_Hidden'), hgexport('factorystyle'), 'Format', 'png');
crop(fullfile(pubpath,'Rating_Open_Hidden.png'));

summary_rating_placebo_control=forest_plotter(df.GIV_stats_rating(~open_hidden),...
              'study_ID_texts',df.study_citations(~open_hidden),...
              'outcome_label','Pain ratings (Hedges''g)',...
              'type','random',...
              'summary_stat','g',...
              'with_outlier',0,...
              'WI_subdata',{},...
              'box_scaling',1,...
              'X_scale',2);

hgexport(gcf, fullfile(pubpath,'Rating_Placebo_Control'), hgexport('factorystyle'), 'Format', 'svg');
hgexport(gcf, fullfile(pubpath,'Rating_Placebo_Control'), hgexport('factorystyle'), 'Format', 'png');
crop(fullfile(pubpath,'Rating_Placebo_Control.png'));

% summary_rating_placebo_notreatment=forest_plotter(df.GIV_stats_rating(placebo_notreatment),...
%               'study_ID_texts',df.study_citations(placebo_notreatment),...
%               'outcome_label','Pain ratings (Hedges''g)',...
%               'type','random',...
%               'summary_stat','g',...
%               'with_outlier',0,...
%               'WI_subdata',{},...
%               'box_scaling',1,...
%               'X_scale',2);
% 
% hgexport(gcf, fullfile(pubpath,'Placebo_NoTreatment'), hgexport('factorystyle'), 'Format', 'svg');
% hgexport(gcf, fullfile(pubpath,'Placebo_NoTreatment'), hgexport('factorystyle'), 'Format', 'png');
% crop(fullfile(pubpath,'Placebo_NoTreatment.png'));


summary_ratings_open_hidden_vs_placebo_control=compare_GIV_summary(summary_rating_open_hidden,summary_rating_placebo_control);
fprintf('Sub-group difference in ratings for studies involving open/hidden vs placebo/control (based on random effects statistics) is %0.2f 95%%CI [%0.2f, %0.2f], z = %0.2f, p=%0.3f\n',...
     summary_ratings_open_hidden_vs_placebo_control.g_diff.random.delta,...
     summary_ratings_open_hidden_vs_placebo_control.g_diff.random.CI_lo,...
     summary_ratings_open_hidden_vs_placebo_control.g_diff.random.CI_hi,...
     summary_ratings_open_hidden_vs_placebo_control.g_diff.random.z,...
     summary_ratings_open_hidden_vs_placebo_control.g_diff.random.p);

%% Analysis for NPS
summary_NPS_open_hidden=forest_plotter(df.GIV_stats_NPS(open_hidden),...
              'study_ID_texts',df.study_citations(open_hidden),...
              'outcome_label','NPS response (Hedges''g)',...
              'type','random',...
              'summary_stat','g',...
              'with_outlier',0,...
              'WI_subdata',{},...
              'box_scaling',1,...
              'X_scale',2);

hgexport(gcf, fullfile(pubpath,'NPS_Open_Hidden'), hgexport('factorystyle'), 'Format', 'svg');
hgexport(gcf, fullfile(pubpath,'NPS_Open_Hidden'), hgexport('factorystyle'), 'Format', 'png');
crop(fullfile(pubpath,'NPS_Open_Hidden.png'));

summary_NPS_placebo_control=forest_plotter(df.GIV_stats_NPS(~open_hidden),...
              'study_ID_texts',df.study_citations(~open_hidden),...
              'outcome_label','NPS response (Hedges''g)',...
              'type','random',...
              'summary_stat','g',...
              'with_outlier',0,...
              'WI_subdata',{},...
              'box_scaling',1,...
              'X_scale',2);

hgexport(gcf, fullfile(pubpath,'NPS_Placebo_Control'), hgexport('factorystyle'), 'Format', 'svg');
hgexport(gcf, fullfile(pubpath,'NPS_Placebo_Control'), hgexport('factorystyle'), 'Format', 'png');
crop(fullfile(pubpath,'NPS_Placebo_Control.png'));

% summary_NPS_placebo_notreatment=forest_plotter(df.GIV_stats_NPS(placebo_notreatment),...
%               'study_ID_texts',df.study_citations(placebo_notreatment),...
%               'outcome_label','Pain NPSs (Hedges''g)',...
%               'type','random',...
%               'summary_stat','g',...
%               'with_outlier',0,...
%               'WI_subdata',{},...
%               'box_scaling',1,...
%               'X_scale',2);
% 
% hgexport(gcf, fullfile(pubpath,'Placebo_NoTreatment'), hgexport('factorystyle'), 'Format', 'svg');
% hgexport(gcf, fullfile(pubpath,'Placebo_NoTreatment'), hgexport('factorystyle'), 'Format', 'png');
% crop(fullfile(pubpath,'Placebo_NoTreatment.png'));
% 

summary_NPSs_open_hidden_vs_placebo_control=compare_GIV_summary(summary_NPS_open_hidden,summary_NPS_placebo_control);
fprintf('Sub-group difference in NPSs for studies involving open/hidden vs placebo/control (based on random effects statistics) is %0.2f 95%%CI [%0.2f, %0.2f], z = %0.2f, p=%0.3f\n',...
     summary_NPSs_open_hidden_vs_placebo_control.g_diff.random.delta,...
     summary_NPSs_open_hidden_vs_placebo_control.g_diff.random.CI_lo,...
     summary_NPSs_open_hidden_vs_placebo_control.g_diff.random.CI_hi,...
     summary_NPSs_open_hidden_vs_placebo_control.g_diff.random.z,...
     summary_NPSs_open_hidden_vs_placebo_control.g_diff.random.p);
 
end