function B1_select_for_meta_all()
%% Define cases for the meta-analysis of the full sample

clear
% Add folder with Generic Inverse Variance Methods Functions first
datapath='../../Datasets';

load(fullfile(datapath,'data_frame.mat'));

%% Contrast images selected for meta-analysis:

contrast_select={{'^control_summary',... % atlas
             '^placebo_summary'},...
             {'^control_summary',... % bingel06
             '^placebo_summary'},...
             {'^pain_remi_no_exp',... % bingel11
             '^pain_remi_pos_exp'},...
             {'^Exp1_control_pain_beta.*',... % choi
             '^placebo_summary'},...
             {'^control_summary_.*',... % eippert
             '^placebo_summary_.*'},...
             {'^Painful_touch_control',... % ellingsen
             '^Painful_touch_placebo'},...
             {'^pain_control_0\%_analgesia',... % elsenb
             '^pain_placebo_100\%_analgesia'},...
             {'^pain_post_control_high_pain',... % freeman
             '^pain_post_placebo_high_pain'},...
             {'^control_summary',... % geuter
             '^placebo_summary'},...
             {'^pain_placebo_neg',... % kessner
             '^pain_placebo_pos'},...
             {'^pain_post_control_high_pain',... % kong06
             '^pain_post_placebo_high_pain'},...
             {'^pain_post_control',... % kong09
             '^pain_post_placebo'},...
             {'^pain_control',... % lui
             '^pain_placebo'},...
             {'^Self_Pain_Control_Group',... % ruetgen
             '^Self_Pain_Placebo_Group'},...
             {'^control_summary',... % schenk
             '^placebo_summary'},...
             {'^control_pain',... % they
             '^placebo_pain'},...
             {'^intense-none',... % wager_princeton, pain contrast only >> placebo contrast: '\(intense-none\)control-placebo'
             'NaN'},...
             {'^control_pain',... % wager_michigan
             '^placebo_pain'},...
             {'^control_summary_.*',... % wrobel
             '^placebo_summary_.*'},...
             {'^Pain>NoPain controlling for placebo&interaction',... % zeidan, pain contrast only >> placebo contrast: 'Pla>Control within painful series'
             'NaN'}
        };
       
%% Get data
df.full=struct('con',cell(height(df),1),...
              'pla',cell(height(df),1),...
              'pla_minus_con',cell(height(df),1),...
              'mean_pla_con',cell(height(df),1));
for i=1:length(df.study_id)
    %Load the variably named table into "df"
    raw=df.raw{i,1};
    i_control=(~cellfun(@isempty,regexp(raw.cond,contrast_select{i}{1})));
    i_placebo=(~cellfun(@isempty,regexp(raw.cond,contrast_select{i}{2})));
    df.full(i).con=raw(i_control,:);
    df.full(i).pla=raw(i_placebo,:);
end

%% Add study/variable descriptions needed for meta-analysis

save(fullfile(datapath,'data_frame.mat'),'df');

end
