% Script to crop white-space from Figures generated by MRIcroGL
figpath='/Users/matthiaszunhammer/Dropbox/Boulder_Essen/protocol_and_manuscript/whole_brain/figures'
picpaths=dir([figpath,'*.png']);
picpaths=strcat(figpath,{picpaths.name});
for i=1:length(picpaths)
    crop(picpaths{i});
end


fig2_paths={
'Figure_2B_Fixed_ant.png'
'Figure_2B_Fixed_cut_insula.png'
'Figure_2B_Fixed_cut_medial_left.png'
'Figure_2B_Fixed_cut_medial_right.png'
'Figure_2B_Fixed_left.png'
'Figure_2B_Fixed_post.png'
'Figure_2B_Fixed_right.png'
'Figure_2B_Random_ant.png'
'Figure_2B_Random_cut_insula.png'
'Figure_2B_Random_cut_medial_left.png'
'Figure_2B_Random_cut_medial_right.png'
'Figure_2B_Random_left.png'
'Figure_2B_Random_post.png'
'Figure_2B_Random_right.png'
'Figure_3B_r_Random_ant.png'
'Figure_3B_r_Random_cut_medial_left.png'
'Figure_3B_r_Random_cut_medial_right.png'
'Figure_3B_r_Random_cut_thalamus.png'
'Figure_3B_r_Random_left.png'
'Figure_3B_r_Random_post.png'
'Figure_3B_r_Random_right.png'
'Figure_S10_g_placebo_conserv.png'
'Figure_S10_r_conservative_Random_ant.png'
'Figure_S10_r_conservative_Random_cut_medial_left.png'
'Figure_S10_r_conservative_Random_cut_medial_right.png'
'Figure_S10_r_conservative_Random_cut_thalamus.png'
'Figure_S10_r_conservative_Random_left.png'
'Figure_S10_r_conservative_Random_post.png'
'Figure_S10_r_conservative_Random_right.png'
    };
for i=1:length(fig2_paths)
crop(fullfile(figpath,fig2_paths{i}));
end
