% Script to crop white-space from Figures generated by MRIcroGL
figpath='/Users/matthiaszunhammer/Dropbox/Boulder_Essen/Protocol_and_Manuscript/whole_brain/figures/'
picpaths=dir([figpath,'*.png']);
picpaths=strcat(figpath,{picpaths.name});
for i=1:length(picpaths)
    crop(picpaths{i});
end


fig2_paths={
'Figure_3B_r_Random_ant.png'
'Figure_3B_r_Random_cut_thalamus.png'
'Figure_3B_r_Random_cut_medial_left.png'
'Figure_3B_r_Random_cut_medial_right.png'
'Figure_3B_r_Random_left.png'
'Figure_3B_r_Random_post.png'
'Figure_3B_r_Random_right.png'
    };
for i=1:length(fig2_paths)
crop(fullfile(figure_path,fig2_paths{i}));
end
