function matthias_bar_plot_similarity(values,SE_values,wedgenames,varargin)
hold on
% Flip negative values (direction of effect is color-coded below)
posvalues=values>0;
values(~posvalues)=values(~posvalues)*-1;
% Color-code negative direction of effect
plot(values(~posvalues),...
    find(~posvalues),...
    '+','MarkerSize',12,...
    'LineWidth',5,...
    'Color',[.4 .4 1]);
line([values(~posvalues)-SE_values(~posvalues),values(~posvalues)+SE_values(~posvalues)]',...
    [find(~posvalues),find(~posvalues)]',...
    'LineWidth',5,...
    'Color',[.4 .4 1]);
% Color-code positive direction of effect
plot(values(posvalues),...
    find(posvalues),...
    '+','MarkerSize',12,...
    'LineWidth',5,...
    'Color',[1 .4 .4]);
line([values(posvalues)-SE_values(posvalues),values(posvalues)+SE_values(posvalues)]',...
    [find(posvalues),find(posvalues)]',...
    'LineWidth',5,...
    'Color',[1 .4 .4])
%Set ticklabels
yticks(1:length(values))
yticklabels(wedgenames)
b=gca;
b.YLim(1)=0;
b.YLim(2)=length(values)+1;
%clip to 0 to ease figure arrangement
b.XLim(1)=0; %clip to 0 to ease figure arrangement
hold off
end