%% Meta-Analysis & Forest Plot

clear
% Add folder with Generic Inverse Variance Methods Functions first
addpath('../A_Analysis_GIV_Functions/')
datapath='../../Datasets';

load(fullfile(datapath,'AllData.mat'))

studies={  'atlas'
           'bingel11'};

% studyIDtexts={
%             'Atlas et al. 2012: Remifentanil (~0.884 ng/ml) vs saline infusion (across open & hidden)|heat';...
% 			'Bingel et al. 2011: Remifentanil (~0.800 ng/ml) vs saline infusion (baseline vs open & hidden)|heat';...
%             };

studyIDtexts={
            'Atlas et al. 2012: Remifentanil vs saline infusion';...
			'Bingel et al. 2011: Remifentanil infusion vs baseline ';...
            };


        % The asteriks "*" indicates that for these data-sets only rating101
        % contrasts were available. Therefore standardized effect sizes (d
        % and hedges g) were imputed using the mean average within-subject
        % correlation for ratings in all other studies, which was: 0.5143
        % (obtained by running the code below with replacing all imputed r's with NaN for all withinMetastats functions, then nanmean([stats.r]))
%% Select data STUDIES

%'Atlas'
%?Pain Placebo NoRemi"      = HiPain Open Stimulation + HiPain Open ExpectationPeriod
%?Pain Placebo Remi"           = HiPain Open Stimulation + HiPain Open ExpectationPeriod + HiPain Open RemiConz
%?Pain NoPlacebo NoRemi"  = HiPain Hidden Stimulation + HiPain Hidden ExpectationPeriod
%?Pain NoPlacebo Remi"       = HiPain Hidden Stimulation + HiPain Hidden ExpectationPeriod + HiPain Open RemiConz

% Effect of remi vs no-remi corresponds to estimated mean plateau effect of
% 0.043 micro-g/kg/min (individual) OR 0.884 ng/ml (absolute)
% across hidden and open administration periods

baseline=mean(...
        [df{(strcmp(df.studyID,'atlas')&~cellfun(@isempty,regexp(df.cond,'StimHiPain_Open_Stimulation'))),'rating101'},...
        df{(strcmp(df.studyID,'atlas')&~cellfun(@isempty,regexp(df.cond,'StimHiPain_Hidden_Stimulation'))),'rating101'}],...
        2);
remi=mean(...
        [df{(strcmp(df.studyID,'atlas')&~cellfun(@isempty,regexp(df.cond,'StimHiPain_Open_Stimulation'))),'rating101'}+...
        df{(strcmp(df.studyID,'atlas')&~cellfun(@isempty,regexp(df.cond,'StimHiPain_Open_RemiConz'))),'rating101'},...
        df{(strcmp(df.studyID,'atlas')&~cellfun(@isempty,regexp(df.cond,'StimHiPain_Hidden_Stimulation'))),'rating101'}+...
        df{(strcmp(df.studyID,'atlas')&~cellfun(@isempty,regexp(df.cond,'StimHiPain_Hidden_RemiConz'))),'rating101'}],...
        2);
i=find(strcmp(studies,'atlas'));
stats(i)=withinMetastats(remi,baseline);

%'bingel11'
baseline=df((strcmp(df.studyID,'bingel11')&strcmp(df.cond,'pain_baseline')),'rating101');
remi=mean(...
        [df{(strcmp(df.studyID,'bingel11')&strcmp(df.cond,'pain_remi_neg_exp')),'rating101'},...
         df{(strcmp(df.studyID,'bingel11')&strcmp(df.cond,'pain_remi_pos_exp')),'rating101'},...
         df{(strcmp(df.studyID,'bingel11')&strcmp(df.cond,'pain_remi_no_exp')),'rating101'}],...
        2);
i=find(strcmp(studies,'bingel11'));
stats(i)=withinMetastats(remi,baseline);


%% Summarize all studies, weigh by SE
% Summary analysis+ Forest Plot
ForestPlotter(stats,...
              'studyIDtexts',studyIDtexts,...
              'outcomelabel','NPS-Response (Hedge''s {\itg})',...
              'type','random',...
              'summarystat','g',...
              'withoutlier',0,...
              'WIsubdata',1,...
              'NOsummary',0,...
              'textoffset',0.1,...
              'boxscaling',0.5);
          
hgexport(gcf, 'NPS_remifentanil_effects.svg', hgexport('factorystyle'), 'Format', 'svg'); 
hgexport(gcf, '../../Protocol_and_Manuscript/NPS_validation/Figures/Figure6x', hgexport('factorystyle'), 'Format', 'svg');

%close all;

