%% Placebo-response (ratings) vs placebo-response NPS

clear
% Add folder with Generic Inverse Variance Methods Functions first
addpath('/Users/matthiaszunhammer/Dropbox/Boulder_Essen/Analysis/A_Analysis_GIV_Functions/')
load('A1_Full_Sample.mat')


studyIDtexts={
            'Atlas et al. 2012';...
			'Bingel et al. 2006';...
			'Bingel et al. 2011';...
			'Choi et al. 2011';...
			'Eippert et al. 2009';...
			'Ellingsen et al. 2013';...
            'Elsenbruch et al. 2012';...
            'Freeman et al. 2015';...
            'Geuter et al. 2013';...
            'Kessner et al. 2014';...
            'Kong et al. 2006';...
            'Kong et al. 2009';...
            'Lui et al. 2010';...
            'Ruetgen et al. 2015'
            'Schenk et al. 2015'
            'Theysohn et al. 2009';...
            'Wager et al. 2004, Study 1';...
            'Wager et al. 2004, Study 2';...
            'Wrobel et al. 2014'
            'Zeidan et al. 2015';...
            };
%% First calculate meta-(one-sample) as usual for ratings
r=find(strcmp(df_full.variables,'stimint'));
n=find(strcmp(df_full.variables,'NPSraw'));

for i=1:length(df_full.studies) % Calculate for all studies except...
    if df_full.consOnlyRating(i)==0 %...data-sets where both pla and con is available
        if df_full.BetweenSubject(i)==0 %Within-subject studies
           stats.rating(i)=withinMetastats(nanmean([df_full.pladata{i}(:,r),df_full.condata{i}(:,r)],2),0);
           stats.NPSraw(i)=withinMetastats(nanmean([df_full.pladata{i}(:,n),df_full.condata{i}(:,n)],2),0);
        elseif df_full.BetweenSubject(i)==1 %Between-subject studies
           stats.rating(i)=withinMetastats([df_full.pladata{i}(:,r);df_full.condata{i}(:,r)],0);
           stats.NPSraw(i)=withinMetastats([df_full.pladata{i}(:,n);df_full.condata{i}(:,n)],0); 
        end
    end

end

