%% Placebo-response (ratings) vs placebo-response NPS

clear
% Add folder with Generic Inverse Variance Methods Functions first
addpath('/Users/matthiaszunhammer/Dropbox/Boulder_Essen/Analysis/A_Analysis_GIV_Functions/')
load('A1_Full_Sample.mat')


studyIDtexts={
            'Atlas et al. 2012';...
			'Bingel et al. 2006';...
			'Bingel et al. 2011';...
			'Choi et al. 2011';...
			'Eippert et al. 2009';...
			'Ellingsen et al. 2013';...
            'Elsenbruch et al. 2012';...
            'Freeman et al. 2015';...
            'Geuter et al. 2013';...
            'Kessner et al. 2014';...
            'Kong et al. 2006';...
            'Kong et al. 2009';...
            'Lui et al. 2010';...
            'Ruetgen et al. 2015'
            'Schenk et al. 2015'
            'Theysohn et al. 2009';...
            'Wager et al. 2004, Study 1';...
            'Wager et al. 2004, Study 2';...
            'Wrobel et al. 2014'
            'Zeidan et al. 2015';...
            };
%% First calculate meta-(one-sample) as usual for ratings
r=find(strcmp(df_full.variables,'stimint'));
n=find(strcmp(df_full.variables,'NPSraw'));

for i=1:length(df_full.studies)
studyID=df_full.pladata{i}
data=vertcat(df_full.pladata{i})
t{i}=array2table(data,'VariableNames',df_full.variables);

end
