%% Comparison of conditioning vs suggesion only studies
clear
load('Full_Sample_Study_Level_Results_Placebo.mat')


studyIDtexts={
            'Atlas et al. 2012';...
			'Bingel et al. 2006';...
			'Bingel et al. 2011';...
			'Choi et al. 2011';...
			'Eippert et al. 2009';...
			'Ellingsen et al. 2013';...
            'Elsenbruch et al. 2012';...
            'Freeman et al. 2015';...
            'Geuter et al. 2013';...
            'Kessner et al. 2014';...
            'Kong et al. 2006';...
            'Kong et al. 2009';...
            'Lui et al. 2010';...
            'Ruetgen et al. 2015'
            'Schenk et al. 2015'
            'Theysohn et al. 2009';...
            'Wager et al. 2004, Study 1';...
            'Wager et al. 2004, Study 2';...
            'Wrobel et al. 2014'
            'Zeidan et al. 2015';...
            };

stats.condi=...
   {'Suggestions'               %	'atlas'
    'Suggestions + Conditioning'%   'bingel'
    'Suggestions + Conditioning'%   'bingel11'
    'Suggestions + Conditioning'%   'choi'
    'Suggestions + Conditioning'%   'eippert'
    'Suggestions'               %   'ellingsen'
    'Suggestions'               %   'elsenbruch'
    'Suggestions + Conditioning'%   'freeman'
    'Suggestions + Conditioning'%   'geuter'
    'Conditioning'              %   'kessner'
    'Suggestions + Conditioning'%   'kong06'
    'Suggestions + Conditioning'%   'kong09'
    'Suggestions + Conditioning'%   'lui'
    'Suggestions + Conditioning'%   'ruetgen'
    'Suggestions'               %   'schenk'
    'Suggestions'               %   'theysohn'
    'Suggestions'               %   'wager04a_princeton'
    'Suggestions + Conditioning'%   'wager04b_michigan'
    'Suggestions + Conditioning'%   'wrobel'
    'Suggestions + Conditioning'};%  'zeidan'

c_and_s=strcmp(stats.condi,'Suggestions + Conditioning');
s_only=strcmp(stats.condi,'Suggestions');
c_only=strcmp(stats.condi,'Conditioning');


%% Analysis for ratings
summary_rating_c_and_s=ForestPlotter(stats.rating(c_and_s),...
              'studyIDtexts',studyIDtexts(c_and_s),...
              'outcomelabel','Pain ratings (Hedges''g)',...
              'type','random',...
              'summarystat','g',...
              'withoutlier',0,...
              'WIsubdata',0,...
              'boxscaling',1,...
              'Xscale',2);

hgexport(gcf, '../../Protocol_and_Manuscript/NPS_placebo/NEJM/Figures/Placebo_Effect_Ratings_Conditioning_and_Suggestions', hgexport('factorystyle'), 'Format', 'svg');
hgexport(gcf, '../../Protocol_and_Manuscript/NPS_placebo/NEJM/Figures/Placebo_Effect_Ratings_Conditioning_and_Suggestions', hgexport('factorystyle'), 'Format', 'png');
crop('../../Protocol_and_Manuscript/NPS_placebo/NEJM/Figures/Placebo_Effect_Ratings_Conditioning_and_Suggestions.png');

summary_rating_s=ForestPlotter(stats.rating(s_only),...
              'studyIDtexts',studyIDtexts(s_only),...
              'outcomelabel','Pain ratings (Hedges''g)',...
              'type','random',...
              'summarystat','g',...
              'withoutlier',0,...
              'WIsubdata',0,...
              'boxscaling',1,...
              'Xscale',2);

hgexport(gcf, '../../Protocol_and_Manuscript/NPS_placebo/NEJM/Figures/Placebo_Effect_Ratings_Suggestions', hgexport('factorystyle'), 'Format', 'svg');
hgexport(gcf, '../../Protocol_and_Manuscript/NPS_placebo/NEJM/Figures/Placebo_Effect_Ratings_Suggestions', hgexport('factorystyle'), 'Format', 'png');
crop('../../Protocol_and_Manuscript/NPS_placebo/NEJM/Figures/Placebo_Effect_Ratings_Suggestions.png');

summary_rating_c=ForestPlotter(stats.rating(c_only),...
              'studyIDtexts',studyIDtexts(c_only),...
              'outcomelabel','Pain ratings (Hedges''g)',...
              'type','random',...
              'summarystat','g',...
              'withoutlier',0,...
              'WIsubdata',0,...
              'boxscaling',1,...
              'Xscale',2);

hgexport(gcf, '../../Protocol_and_Manuscript/NPS_placebo/NEJM/Figures/Placebo_Effect_Ratings_Conditioning', hgexport('factorystyle'), 'Format', 'svg');
hgexport(gcf, '../../Protocol_and_Manuscript/NPS_placebo/NEJM/Figures/Placebo_Effect_Ratings_Conditioning', hgexport('factorystyle'), 'Format', 'png');
crop('../../Protocol_and_Manuscript/NPS_placebo/NEJM/Figures/Placebo_Effect_Ratings_Conditioning.png');


summary_ratings_c_and_s_vs_s=compareGIVsummary(summary_rating_c_and_s,summary_rating_s);
fprintf('Sub-group difference in ratings for studies involving placebo conditioning + suggestions vs suggestion only (based on random effects statistics) is %0.2f 95%%CI [%0.2f, %0.2f], z = %0.2f, p=%0.3f\n',...
     summary_ratings_c_and_s_vs_s.g_diff.random.delta,...
     summary_ratings_c_and_s_vs_s.g_diff.random.CI_lo,...
     summary_ratings_c_and_s_vs_s.g_diff.random.CI_hi,...
     summary_ratings_c_and_s_vs_s.g_diff.random.z,...
     summary_ratings_c_and_s_vs_s.g_diff.random.p);

summary_ratings_c_and_s_vs_c=compareGIVsummary(summary_rating_c_and_s,summary_rating_c);
fprintf('Sub-group difference in ratings for studies involving placebo conditioning + suggestions vs conditioning only (based on random effects statistics) is %0.2f 95%%CI [%0.2f, %0.2f], z = %0.2f, p=%0.3f\n',...
     summary_ratings_c_and_s_vs_c.g_diff.random.delta,...
     summary_ratings_c_and_s_vs_c.g_diff.random.CI_lo,...
     summary_ratings_c_and_s_vs_c.g_diff.random.CI_hi,...
     summary_ratings_c_and_s_vs_c.g_diff.random.z,...
     summary_ratings_c_and_s_vs_c.g_diff.random.p);
 
summary_ratings_s_vs_c=compareGIVsummary(summary_rating_s,summary_rating_c);
fprintf('Sub-group difference in ratings for studies involving placebo suggestions only vs conditioning only (based on random effects statistics) is %0.2f 95%%CI [%0.2f, %0.2f], z = %0.2f, p=%0.3f\n',...
     summary_ratings_s_vs_c.g_diff.random.delta,...
     summary_ratings_s_vs_c.g_diff.random.CI_lo,...
     summary_ratings_s_vs_c.g_diff.random.CI_hi,...
     summary_ratings_s_vs_c.g_diff.random.z,...
     summary_ratings_s_vs_c.g_diff.random.p); 
 
%% Analysis for NPS
summary_NPS_cond=ForestPlotter(stats.NPS(conditioning),...
              'studyIDtexts',studyIDtexts(conditioning),...
              'outcomelabel','NPS response (Hedges''g)',...
              'type','random',...
              'summarystat','g',...
              'withoutlier',0,...
              'WIsubdata',0,...
              'boxscaling',1,...
              'Xscale',2);

hgexport(gcf, '../../Protocol_and_Manuscript/NPS_placebo/NEJM/Figures/Placebo_Effect_NPS_Conditioning', hgexport('factorystyle'), 'Format', 'svg');
hgexport(gcf, '../../Protocol_and_Manuscript/NPS_placebo/NEJM/Figures/Placebo_Effect_NPS_Conditioning', hgexport('factorystyle'), 'Format', 'png');
crop('../../Protocol_and_Manuscript/NPS_placebo/NEJM/Figures/Placebo_Effect_NPS_Conditioning.png');

summary_NPS_sugg=ForestPlotter(stats.NPS(~conditioning),...
              'studyIDtexts',studyIDtexts(~conditioning),...
              'outcomelabel','NPS response (Hedges''g)',...
              'type','random',...
              'summarystat','g',...
              'withoutlier',0,...
              'WIsubdata',0,...
              'boxscaling',1,...
              'Xscale',2);

hgexport(gcf, '../../Protocol_and_Manuscript/NPS_placebo/NEJM/Figures/Placebo_Effect_NPS_NoConditioning', hgexport('factorystyle'), 'Format', 'svg');
hgexport(gcf, '../../Protocol_and_Manuscript/NPS_placebo/NEJM/Figures/Placebo_Effect_NPS_NoConditioning', hgexport('factorystyle'), 'Format', 'png');
crop('../../Protocol_and_Manuscript/NPS_placebo/NEJM/Figures/Placebo_Effect_NPS_NoConditioning.png');

summary_NPS_cond_vs_sugg=compareGIVsummary(summary_NPS_cond,summary_NPS_sugg);
fprintf('Sub-group difference of NPS for conditioning vs non-conditioning studies (based on random effects statistics) is %0.2f 95%%CI [%0.2f, %0.2f], z = %0.2f, p=%0.3f\n',...
     summary_NPS_cond_vs_sugg.g_diff.random.delta,...
     summary_NPS_cond_vs_sugg.g_diff.random.CI_lo,...
     summary_NPS_cond_vs_sugg.g_diff.random.CI_hi,...
     summary_NPS_cond_vs_sugg.g_diff.random.z,...
     summary_NPS_cond_vs_sugg.g_diff.random.p);
%% Analysis for SIIPS
summary_SIIPS_cond=ForestPlotter(stats.SIIPS(conditioning),...
              'studyIDtexts',studyIDtexts(conditioning),...
              'outcomelabel','NPS response (Hedges''g)',...
              'type','random',...
              'summarystat','g',...
              'withoutlier',0,...
              'WIsubdata',0,...
              'boxscaling',1,...
              'Xscale',2);

hgexport(gcf, '../../Protocol_and_Manuscript/NPS_placebo/NEJM/Figures/Placebo_Effect_SIIPS_Conditioning', hgexport('factorystyle'), 'Format', 'svg');
hgexport(gcf, '../../Protocol_and_Manuscript/NPS_placebo/NEJM/Figures/Placebo_Effect_SIIPS_Conditioning', hgexport('factorystyle'), 'Format', 'png');
crop('../../Protocol_and_Manuscript/NPS_placebo/NEJM/Figures/Placebo_Effect_SIIPS_Conditioning.png');

summary_SIIPS_sugg=ForestPlotter(stats.SIIPS(~conditioning),...
              'studyIDtexts',studyIDtexts(~conditioning),...
              'outcomelabel','NPS response (Hedges''g)',...
              'type','random',...
              'summarystat','g',...
              'withoutlier',0,...
              'WIsubdata',0,...
              'boxscaling',1,...
              'Xscale',2);

hgexport(gcf, '../../Protocol_and_Manuscript/NPS_placebo/NEJM/Figures/Placebo_Effect_SIIPS_NoConditioning', hgexport('factorystyle'), 'Format', 'svg');
hgexport(gcf, '../../Protocol_and_Manuscript/NPS_placebo/NEJM/Figures/Placebo_Effect_SIIPS_NoConditioning', hgexport('factorystyle'), 'Format', 'png');
crop('../../Protocol_and_Manuscript/NPS_placebo/NEJM/Figures/Placebo_Effect_SIIPS_NoConditioning.png');

summary_SIIPS_cond_vs_sugg=compareGIVsummary(summary_SIIPS_cond,summary_SIIPS_sugg);
fprintf('Sub-group difference of SIIPS for conditioning vs non-conditioning studies (based on random effects statistics) is %0.2f 95%%CI [%0.2f, %0.2f], z = %0.2f, p=%0.3f\n',...
     summary_SIIPS_cond_vs_sugg.g_diff.random.delta,...
     summary_SIIPS_cond_vs_sugg.g_diff.random.CI_lo,...
     summary_SIIPS_cond_vs_sugg.g_diff.random.CI_hi,...
     summary_SIIPS_cond_vs_sugg.g_diff.random.z,...
     summary_SIIPS_cond_vs_sugg.g_diff.random.p);