function Arrange_Renders(annotate)
    % Script to crop white-space from Figures generated by MRIcroGL
    basepath='/Users/matthiaszunhammer/Dropbox/Boulder_Essen/Protocol_and_Manuscript/whole_brain/figures/';

    %% Add legends to cerebellar figures
    add_legend_to_image([basepath,'Figure_2_Render_post_cerebellum.png'],1);
    add_legend_to_image([basepath,'Figure_3_Render_post_cerebellum.png'],1);
    add_legend_to_image([basepath,'Figure_S8_Render_post_cerebellum.png'],0);

    %%
    figs={'Figure_2','Figure_3','Figure_S8'};
    
    imgpaths={
            '_Render_ant.png'
            '_Render_left.png'
            '_Render_right.png'
            '_Render_post.png'
            '_Render_cut_insula.png'
            '_Render_cut_medial_left.png'
            '_Render_cut_medial_right.png'
            '_Render_post_cerebellum_w_legend.png'};
    % Text to appear in upper left corner of each figure
    figure_labels={'Anterior'
         'Left'
         'Right'
         'Posterior'
         'Anterior-coronal'
         'Left-saggital'
         'Right-saggital'
         'Superior cerebellum'
        };
    
    arrange_imgs(basepath,figs,imgpaths,figure_labels,annotate);

    function arrange_imgs(basepath,figs,imgpaths,imglabels,annotate)
        % Read images
        for j=1:length(figs)
            currimgs=strcat(figs(j),imgpaths);
            
            img=cell(size(currimgs));
            for i=1:length(currimgs)
                img{i}=imread(strcat(basepath,currimgs{i}));
            end
            
            % Create figure layout
            figure('Position',[0,0,1200,500])
            nrow=2;
            ncol=length(currimgs)/nrow;
            hrow=1/nrow;
            wcol=1/ncol;
            ha=tight_subplot(nrow,ncol,[0.025,0],0,0);

            % Add images and annotations to layout
            for i=1:length(currimgs)
                irow=ceil(i/ncol);
                icol=ceil(i-(irow-1)*ncol);
                axes(ha(i));
                imshow(img{i});
                if annotate==1
                    annotation('textbox',[wcol*icol-0.25 1-hrow*irow+0.4 .1 .1],...
                    'String', imglabels{i},'FontSize',14, 'LineStyle','none');
                end
            end
        print(fullfile(basepath,[figs{j},'_summary','.png']),'-dpng','-r600'); 
        end
    end
close all
end