run('A_MetaAnalysis_NPS_Basic.m')
run('A_MetaAnalysis_NPS_Inclusive.m')
run('A_MetaAnalysis_NPS_Pain_vs_Baseline_Basic.m')
run('A_MetaAnalysis_NPS_Responder.m')
run('A_MetaAnalysis_Ratings_Basic.m')
run('A_MetaAnalysis_Ratings_Inclusive.m')
run('A_MetaAnalysis_Pain_vs_Baseline_Inclusive.m')