%% Placebo-response (ratings) vs placebo-response NPS


% Add folder with Generic Inverse Variance Methods Functions first
addpath('../A_Analysis_GIV_Functions/')
load('A1_Full_Sample.mat')

% !!!!! These must be in the same order as listed under "studies" !!!!

% studyIDtexts={
%             'Atlas et al. 2012: Hidden vs open remifentanil drip infusion (expectation period)| heat';...
% 			'Bingel et al. 2006: Control vs placebo cream | laser';...
% 			'Bingel et al. 2011: No vs positive expectations | heat';...
% 			'Choi et al. 2011: No vs low & high effective placebo drip infusion (Exp1 and 2) | electrical';...
% 			'Eippert et al. 2009: Control vs placebo cream (saline & naloxone group) | heat (early & late)';...
% 			'Ellingsen et al. 2013: Pre vs post placebo nasal spray | heat';...
%             'Elsenbruch et al. 2012: No vs certain placebo drip infusion | distension';...
%             'Freeman et al. 2015: Control vs placebo cream | heat';...
%             'Geuter et al. 2013: Control vs weak & strong placebo cream | heat (early & late)';...
%             'Huber et al. 2013: Red vs green cue signifying sham TENS off vs on | laser';...
%             'Kessner et al. 2014: Negative vs positive treatment expectation group | heat';...
%             'Kong et al. 2006: Control vs placebo acupuncture | heat (high & low)';...
%             'Kong et al. 2009: Control vs placebo sham acupuncture | heat';...
%             'Ruetgen et al. 2015: No treatment vs placebo pill group  | electrical'
%             'Schenk et al. 2015:  Control vs placebo (saline & lidocain) | heat'
%             'Theysohn et al. 2009: No vs certain placebo drip infusion | distension';...
%             'Wager et al. 2004, Study 1: Control vs placebo cream | heat*';...
%             'Wager et al. 2004, Study 2: Control vs placebo cream | electrical*';...
%             'Wrobel et al. 2014: Control vs placebo cream (saline & haldol group) | heat(early & late)'
%             'Zeidan et al. 2015: Control vs placebo cream (placebo group) | heat*';...
%             };

studyIDtexts={
            'Atlas et al. 2012';...
			'Bingel et al. 2006';...
			'Bingel et al. 2011';...
			'Choi et al. 2011';...
			'Eippert et al. 2009';...
			'Ellingsen et al. 2013';...
            'Elsenbruch et al. 2012';...
            'Freeman et al. 2015';...
            'Geuter et al. 2013';...
            'Kessner et al. 2014';...
            'Kong et al. 2006';...
            'Kong et al. 2009';...
            'Lui et al. 2010';...
            'Ruetgen et al. 2015'
            'Schenk et al. 2015'
            'Theysohn et al. 2009';...
            %'Wager et al. 2004, Study 1';...
            'Wager et al. 2004, Study 2';...
            'Wrobel et al. 2014'
            %'Zeidan et al. 2015';...
            };
%% First calculate meta-stats for stimInt vs NPS (control condition only)
v1=find(strcmp(df_full.variables,'stimInt'));
v2=find(strcmp(df_full.variables,'NPS'));

for i=1:length(df_full.studies) % Calculate for all studies except...
    if df_full.consOnlyNPS(i)==0 %...data-sets where both pla and con is available
        if df_full.BetweenSubject(i)==0
        stats.NPSvsStimInt(i)=withinMetastats(nanmean([df_full.condata{i}(:,v1),df_full.pladata{i}(:,v1)],2),...
                                        nanmean([df_full.condata{i}(:,v2),df_full.pladata{i}(:,v2)],2));
        elseif df_full.BetweenSubject(i)==1
        stats.NPSvsStimInt(i)=withinMetastats([df_full.condata{i}(:,v1);df_full.pladata{i}(:,v1)],...
                                        [df_full.condata{i}(:,v2);df_full.pladata{i}(:,v2)]);    
        end
    end
end

summary=GIVsummary(stats.NPSvsStimInt,'r');

%% Second calculate meta-stats for stimInt vs SIIPS (control condition only)
v1=find(strcmp(df_full.variables,'stimInt'));
v2=find(strcmp(df_full.variables,'SIIPS'));

for i=1:length(df_full.studies) % Calculate for all studies except...
    if df_full.consOnlyNPS(i)==0 %...data-sets where both pla and con is available
        if df_full.BetweenSubject(i)==0
        stats.SIIPSvsStimInt(i)=withinMetastats(nanmean([df_full.condata{i}(:,v1),df_full.pladata{i}(:,v1)],2),...
                                        nanmean([df_full.condata{i}(:,v2),df_full.pladata{i}(:,v2)],2));
        elseif df_full.BetweenSubject(i)==1
        stats.SIIPSvsStimInt(i)=withinMetastats([df_full.condata{i}(:,v1);df_full.pladata{i}(:,v1)],...
                                        [df_full.condata{i}(:,v2);df_full.pladata{i}(:,v2)]);    
        end
    end
end

summary=GIVsummary(stats.SIIPSvsStimInt,'r');

%% Forrest plots
ForestPlotter(stats.NPSvsStimInt,...
              'studyIDtexts',studyIDtexts,...
              'outcomelabel','Correlation NPS vs Stimulus Intensity (r)',...
              'type','random',...
              'summarystat','r',...
              'withoutlier',0,...
              'WIsubdata',0,...
              'boxscaling',1);

 hgexport(gcf, '../../Protocol_and_Manuscript/NPS_placebo/NEJM/Figures/Corr_NPS_vs_individual_StimulusIntensity', hgexport('factorystyle'), 'Format', 'svg');
 hgexport(gcf, '../../Protocol_and_Manuscript/NPS_placebo/NEJM/Figures/Corr_NPS_vs_individual_StimulusIntensity', hgexport('factorystyle'), 'Format', 'png');
 crop('../../Protocol_and_Manuscript/NPS_placebo/NEJM/Figures/Corr_NPS_vs_individual_StimulusIntensity.png');



ForestPlotter(stats.SIIPSvsStimInt,...
              'studyIDtexts',studyIDtexts,...
              'outcomelabel','Correlation SIIPS vs Stimulus Intensity (r)',...
              'type','random',...
              'summarystat','r',...
              'withoutlier',0,...
              'WIsubdata',0,...
              'boxscaling',1);

 hgexport(gcf, '../../Protocol_and_Manuscript/NPS_placebo/NEJM/Figures/Corr_SIIPS_vs_individual_StimulusIntensity', hgexport('factorystyle'), 'Format', 'svg');
 hgexport(gcf, '../../Protocol_and_Manuscript/NPS_placebo/NEJM/Figures/Corr_SIIPS_vs_individual_StimulusIntensity', hgexport('factorystyle'), 'Format', 'png');
 crop('../../Protocol_and_Manuscript/NPS_placebo/NEJM/Figures/Corr_SIIPS_vs_individual_StimulusIntensity.png');
close all;
