%% Meta-Analysis & Forest Plot



% Add folder with Generic Inverse Variance Methods Functions first
addpath('../A_Analysis_GIV_Functions/')
datapath='../../Datasets';

load(fullfile(datapath,'AllData.mat'))

studies={'atlas'
         'bingel11'};

% studyIDtexts={
%             'Atlas et al. 2012: Remifentanil (~0.884 ng/ml) vs saline infusion (across open & hidden)|heat';...
% 			'Bingel et al. 2011: Remifentanil (~0.800 ng/ml) vs saline infusion (baseline vs open & hidden)|heat';...
%             };

studyIDtexts={
            'Atlas et al. 2012: Remifentanil vs saline infusion';...
			'Bingel et al. 2011: Remifentanil infusion vs baseline ';...
            };


        % The asteriks "*" indicates that for these data-sets only rating
        % contrasts were available. Therefore standardized effect sizes (d
        % and hedges g) were imputed using the mean average within-subject
        % correlation for ratings in all other studies, which was: 0.5143
        % (obtained by running the code below with replacing all imputed r's with NaN for all withinMetastats functions, then nanmean([remi_stats.r]))
%% Select data STUDIES

%'Atlas'
%?Pain Placebo NoRemi"      = HiPain Open Stimulation + HiPain Open ExpectationPeriod
%?Pain Placebo Remi"           = HiPain Open Stimulation + HiPain Open ExpectationPeriod + HiPain Open RemiConz
%?Pain NoPlacebo NoRemi"  = HiPain Hidden Stimulation + HiPain Hidden ExpectationPeriod
%?Pain NoPlacebo Remi"       = HiPain Hidden Stimulation + HiPain Hidden ExpectationPeriod + HiPain Open RemiConz

% Effect of remi vs no-remi corresponds to estimated mean plateau effect of
% 0.043 micro-g/kg/min (individual) OR 0.884 ng/ml (absolute)
% across hidden and open administration periods

baseline=mean(...
        [df{(strcmp(df.studyID,'atlas')&~cellfun(@isempty,regexp(df.cond,'StimHiPain_Open_Stimulation'))),'rating'},...
        df{(strcmp(df.studyID,'atlas')&~cellfun(@isempty,regexp(df.cond,'StimHiPain_Hidden_Stimulation'))),'rating'}],...
        2);
remi=mean(...
        [df{(strcmp(df.studyID,'atlas')&~cellfun(@isempty,regexp(df.cond,'StimHiPain_Open_Stimulation'))),'rating'}+...
        df{(strcmp(df.studyID,'atlas')&~cellfun(@isempty,regexp(df.cond,'StimHiPain_Open_RemiConz'))),'rating'},...
        df{(strcmp(df.studyID,'atlas')&~cellfun(@isempty,regexp(df.cond,'StimHiPain_Hidden_Stimulation'))),'rating'}+...
        df{(strcmp(df.studyID,'atlas')&~cellfun(@isempty,regexp(df.cond,'StimHiPain_Hidden_RemiConz'))),'rating'}],...
        2);
    
baseline_NPS=mean(...
        [df{(strcmp(df.studyID,'atlas')&~cellfun(@isempty,regexp(df.cond,'StimHiPain_Open_Stimulation'))),'NPS'},...
        df{(strcmp(df.studyID,'atlas')&~cellfun(@isempty,regexp(df.cond,'StimHiPain_Hidden_Stimulation'))),'NPS'}],...
        2);
remi_NPS=mean(...
        [df{(strcmp(df.studyID,'atlas')&~cellfun(@isempty,regexp(df.cond,'StimHiPain_Open_Stimulation'))),'NPS'}+...
        df{(strcmp(df.studyID,'atlas')&~cellfun(@isempty,regexp(df.cond,'StimHiPain_Open_RemiConz'))),'NPS'},...
        df{(strcmp(df.studyID,'atlas')&~cellfun(@isempty,regexp(df.cond,'StimHiPain_Hidden_Stimulation'))),'NPS'}+...
        df{(strcmp(df.studyID,'atlas')&~cellfun(@isempty,regexp(df.cond,'StimHiPain_Hidden_RemiConz'))),'NPS'}],...
        2);
    
i=find(strcmp(studies,'atlas'));
remi_stats.rating(i)=withinMetastats(remi,baseline);
remi_stats.nps(i)=withinMetastats(remi_NPS,baseline_NPS);

%'bingel11'
baseline=df((strcmp(df.studyID,'bingel11')&strcmp(df.cond,'pain_baseline')),'rating');
remi=mean(...
        [df{(strcmp(df.studyID,'bingel11')&strcmp(df.cond,'pain_remi_neg_exp')),'rating'},...
         df{(strcmp(df.studyID,'bingel11')&strcmp(df.cond,'pain_remi_pos_exp')),'rating'},...
         df{(strcmp(df.studyID,'bingel11')&strcmp(df.cond,'pain_remi_no_exp')),'rating'}],...
        2);
baseline_NPS=df((strcmp(df.studyID,'bingel11')&strcmp(df.cond,'pain_baseline')),'NPS');
remi_NPS=mean(...
        [df{(strcmp(df.studyID,'bingel11')&strcmp(df.cond,'pain_remi_neg_exp')),'NPS'},...
         df{(strcmp(df.studyID,'bingel11')&strcmp(df.cond,'pain_remi_pos_exp')),'NPS'},...
         df{(strcmp(df.studyID,'bingel11')&strcmp(df.cond,'pain_remi_no_exp')),'NPS'}],...
        2);
i=find(strcmp(studies,'bingel11'));
remi_stats.rating(i)=withinMetastats(remi,baseline);
remi_stats.nps(i)=withinMetastats(remi_NPS,baseline_NPS);

save('Remifentanil_Results.mat','remi_stats');

%% Summarize all studies, weigh by SE
% Summary analysis+ Forest Plot
ForestPlotter(remi_stats.rating,...
              'studyIDtexts',studyIDtexts,...
              'outcomelabel','Rating-Response (Hedge''s {\itg})',...
              'type','random',...
              'summarystat','g',...
              'withoutlier',0,...
              'WIsubdata',0,...
              'NOsummary',0,...
              'textoffset',0.1,...
              'boxscaling',0.5,...
              'Xscale',2);
          
hgexport(gcf, 'Rating_remifentanil_effects.svg', hgexport('factorystyle'), 'Format', 'svg'); 
hgexport(gcf, '../../Protocol_and_Manuscript/NPS_placebo/NEJM/Figures/Rating_remifentanil_effects', hgexport('factorystyle'), 'Format', 'svg');

ForestPlotter(remi_stats.nps,...
              'studyIDtexts',studyIDtexts,...
              'outcomelabel','NPS-Response (Hedge''s {\itg})',...
              'type','random',...
              'summarystat','g',...
              'withoutlier',0,...
              'WIsubdata',0,...
              'NOsummary',0,...
              'textoffset',0.1,...
              'boxscaling',0.5,...
              'Xscale',2);
          
hgexport(gcf, 'NPS_remifentanil_effects.svg', hgexport('factorystyle'), 'Format', 'svg'); 
hgexport(gcf, '../../Protocol_and_Manuscript/NPS_placebo/NEJM/Figures/NPS_remifentanil_effects', hgexport('factorystyle'), 'Format', 'svg');

%close all;


%% Plot and summarize placebo effects for these specific studies, weigh by SE

load(fullfile('../E_NPS_Meta_Analysis_Placebo/Full_Sample_Study_Level_Results_Placebo.mat'))

study_index=ismember(stats.studies,{'atlas','bingel11'})
studyIDtexts={
            'Atlas et al. 2012: Open vs hidden infusion';...
			'Bingel et al. 2011: Open vs hidden infusion ';...
            };

% Summary analysis+ Forest Plot
ForestPlotter(stats.rating(study_index),...
              'studyIDtexts',studyIDtexts,...
              'outcomelabel','Rating-Response (Hedge''s {\itg})',...
              'type','random',...
              'summarystat','g',...
              'withoutlier',0,...
              'WIsubdata',0,...
              'NOsummary',0,...
              'textoffset',0.1,...
              'boxscaling',0.5,...
              'Xscale',2);
          
hgexport(gcf, 'Rating_placebo_effects_remi_studies.svg', hgexport('factorystyle'), 'Format', 'svg'); 
hgexport(gcf, '../../Protocol_and_Manuscript/NPS_placebo/NEJM/Figures/Rating_placebo_effects_remi_studies', hgexport('factorystyle'), 'Format', 'svg');

ForestPlotter(stats.NPS(study_index),...
              'studyIDtexts',studyIDtexts,...
              'outcomelabel','NPS-Response (Hedge''s {\itg})',...
              'type','random',...
              'summarystat','g',...
              'withoutlier',0,...
              'WIsubdata',0,...
              'NOsummary',0,...
              'textoffset',0.1,...
              'boxscaling',0.5,...
              'Xscale',2);
          
hgexport(gcf, 'NPS_placebo_effects_remi_studies.svg', hgexport('factorystyle'), 'Format', 'svg'); 
hgexport(gcf, '../../Protocol_and_Manuscript/NPS_placebo/NEJM/Figures/NPS_placebo_effects_remi_studies', hgexport('factorystyle'), 'Format', 'svg');

